backend:
  name: git-gateway
  repo: phortonssf/restaurant-webpage
  branch: master

publish_mode: editorial_workflow
media_folder: "src/img/gallery"

 # Folder where user uploaded files should go


collections: # A list of collections the CMS should be able to edit
  - name: food
    label: "Food Item"
    folder: "site/content/food"
    create: true
    fields:
      - {label: "Name of Item" , name: "Title" , widget: "string"}
      - {label: "Supported Meals", name: "Categories", widget: "list", default: ["Lunch", "Dinner"]}
      - {label: "Ingredients" , name: "Description" , widget: "text"}
      - {label: "Type of Food" , name: "Type" , widget: "string", default: "raw bar"}
      - {label: "Price", name: "price", widget: "string"}
